apiVersion: v1
kind: Service
metadata:
  namespace: ns-app
  name: cafeapp-service
spec:
  selector:
    app: cafeapp
  ports:
    - protocol: TCP
      port: 80 # The port the service is exposed on. can be any port, but 80 is standard for HTTP
      targetPort: 80 # The port your application is listening on. match with containerPort in deployment.yaml and docker webserver exposed port
      nodePort: 30025 # The port on the node to expose the service on. match with extraPortMappings containerPort if in kind config
  type: NodePort
